### ISSUE TITLE
[Question] Status of this project ?

### ISSUE THREAD

**Issue by maustand** [diegohaz/rest#115]
Hi Diego, @diegohaz 
How are you ?.

Just i would like to ask you about the status of this repository ?
is it abandoned project or simply you dont have more time to develop new features ?

This generator is so great and it works perfect, even we are using for our sass webapp on production in my company.

Do you have a pool of features that you would like to add ?
I would like to collaborate and i saw in your TODO that you would like to add websockets support.
If still it is relevant or if there is something that i could help,  let me know.

Reagards

**Comment by awojtczyk** [comment]
+1 I'd like to contribute aswell.

Especially, with login strategies which i mentioned in #113 

@maustand Mauricio, anything special what you have added to the generator so far?

**Comment by diegohaz** [comment]
Hi, @maustand.

The project is active. I just don't have time to code new features at the moment.

Sockets are still a desirable feature. But I don't have enough experience/knowledge with that to evaluate the effort it demands.

**Comment by maustand** [comment]
@diegohaz if you consider, i could create this feature in my fork and we could
WebSockets is not a big deal..

In other hand , it would be great to moderate the issues forum..
Currently i am helping in a few posts that it would be nice to close it because the issues were solved.

If you need a moderator, let me know !


@awojtczyk Only i was updating the dependencies of this repository..
it is a little tricky because i had to do it in my own project that it is in production and there are some dependencies that they can not be updated to the last ones because it breaks the nodejs server..
meanwhile we decide what kinda features we are going to develop,  i think that i will remove supertest-as-promised in the next days, because it is deprecated.

Regards

**Comment by diegohaz** [comment]
Sure, @maustand. I will send you an invitation. Thank you so much for your help.

**Comment by maustand** [comment]
Hi @diegohaz , just i would like to ask you if it would be great to deploy a new version of the generator ?
Is it automatic on npm ? or is npm taking the source code automatically without deploying a new version ?
outside downloading packages, i dont have a lots of experience with npm server..

i saw that there a few tasks on the package.json for publishing a new version of the generator on npm, but i dont know how it works exactly. 
Could you clarify me ?

Regards

**Comment by diegohaz** [comment]
@maustand I've just published a new version with `npm run minor`. Haven't done that yet because of lack of time to write proper release notes (https://github.com/diegohaz/rest/releases).

The steps to publish on npm are:
1. adding your npm user to your machine: `npm adduser` (maybe you need to register to npm, don't remember);
2. running `yarn test` to guarantee that everything is ok;
3. running `npm run patch` (for small features and fixes) or `npm run minor` (for big/break changes).  We are not working with `npm run major` yet (it would create `v1.0.0`, `v2.0.0` etc.).

The third step will automatically create a tag on GitHub. Then, you just need to go to the releases section and write notes.

If you want to do that, tell me your npm user so I give you publish rights there. 🙂

Thank you so much for your help.
