### ISSUE TITLE
Handling Array Of Objects

### ISSUE THREAD

**Issue by vuctechs** [diegohaz/rest#116]
Dear Sir,

I love your generator, it is solving many issues, but I am finding difficulty in handling Schema with Array of Objects, It would be very helpful if you could give me some ideas to update the push data into the array.

I have attached my schema for the reference
![capture](https://user-images.githubusercontent.com/33199237/32144789-feb7f358-bce3-11e7-8aaf-8560346f1981.PNG)
 
Thanks

**Comment by maustand** [comment]
Hi

As i see, Regarding of the schema documentation in  [mongoosejs](http://mongoosejs.com/docs/guide.html)  seems that your schema is ok..

Honestly i dont understand your question or problem, because you are asking about strategies about how you could save/update your data in a collection, but this is more relevant to mongoDB and mongoose.. Not to the Rest:Generator.

Also if you have problems with bodymen and fetching a property that it is array of objects, you could see this post  #112

Could you clarify please ?

Regards

**Comment by vuctechs** [comment]
Dear Sir,

Thank you for your reply, I really want to know how to write a service,
where the service needs to communicate with multiple collections and update
it..


On 5 Nov 2017 4:54 pm, "Mauricio Stand" <notifications@github.com> wrote:

Hi

As i see, Regarding of the schema documentation in mongoosejs
<http://mongoosejs.com/docs/guide.html> seems that your schema is ok..

Honestly i dont understand your question or problem, because you are asking
about strategies about how you could save/update your data in a collection,
but this is more relevant to mongoDB and mongoose.. Not to the
Rest:Generator.

Also if you have problems with bodymen and fetching a property that it is
array of objects, you could see this post #112
<https://github.com/diegohaz/rest/issues/112>

Could you clarify please ?

Regards

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/diegohaz/rest/issues/116#issuecomment-341965863>, or mute
the thread

**Comment by vuctechs** [comment]
Dear Sir,

Will you be able to send a sample service which involves fetching data from
2 collections and send response..

Thanks

**Comment by maustand** [comment]
Hi @vuctechs 

As i see, you dont have problems with the generator and you are asking about how you can create a services..

In this case, i would advice you to read the next articles where you could learn more about the meanStack

https://devcenter.heroku.com/articles/mean-apps-restful-api

In other hand, this generator gives you a good starting point where you would not have to begin from the scratch.
Even you could create a new endpoint via Generator and see how it works.

Only you have to keep in mind the conventions of this generator where Index.js is used for defining the endpoint ( url, parameters , permission ) and controller.js is where you would have to write the function that it would be triggered for the endpoint that you defined in your index.js

In other hand, If you need to fetch data and do multiple operations between collections in mongo, it might mean that you are doing something wrong, specially with your data model structure..
In mongo , you could perform simple relationship joins via [.populate,](http://mongoosejs.com/docs/populate.html) using mongoose ( included in this generator ), Otherwise you could import your 2 collecitons in your controller and perform a sequential query, something like 


1. find my user, view userCollection
2. find myCourses with my userID, via coursesCollection. 
3. fetch data.

Just in case if you dont undestand very well how you could create a good data model in mongo, you should see this [video](https://www.youtube.com/watch?v=-o_VGpJP-Q0&t=1148s) where the microsoft team explain in a very clear way.

Regards

**Comment by vuctechs** [comment]
Thank you sir
