### ISSUE TITLE
Store Front end Keys

### ISSUE THREAD

**Issue by jorgeluisrezende** [diegohaz/rest#143]
I have a question, how can i safely store my api key in my front end?

**Comment by maustand** [comment]
hi

are u refering to the masterkey ?

Regards

**Comment by jorgeluisrezende** [comment]
Yes, i need to create a user singup my front end is a spa made in vue.js.
How could i store that safely?

**Comment by diegohaz** [comment]
@jorgeluisrezende You should not store the master key in the front end. If you are going to use it, your login page should be rendered by a server and call the api from the server (where you can store the master key). Then, you can store the token in cookies and grab it on your SPA.

Alternatively, you can remove the master key protection on auth endpoints and apply another kind of verification, like origin request header, IP rate limit etc. I'm not sure if that's entirely secure though.

Note: we usually want to protect our POST/PATCH/PUT/DELETE endpoints so others cannot create or modify resources in our servers from outside of our site. For the most of those endpoints, user should be logged in, thus we'll have the auth token as a protection. But, for creating users, though, we don't have token yet. That's why we use master key.

**Comment by jorgeluisrezende** [comment]
if i use a file to config that will not be served? can it works? if i use server side render from vue?

**Comment by diegohaz** [comment]
If you are going to make an ajax request, it will appear in the network section on devtools. Anyone can go there, see the request and grab the master key that had been sent.

Vue server side render will work.

**Comment by jorgeluisrezende** [comment]
Maybe can make a login and  singup page at my api server and server it by a iframe in my spa, do you think that can works?

**Comment by jorgeluisrezende** [comment]
is safe store the auth token?

**Comment by diegohaz** [comment]
> Maybe can make a login and singup page at my api server and server it by a iframe in my spa, do you think that can works?

Never tried. You need them to share cookies at least. I'm curious to see it works.

> is safe store the auth token?

It's safe to assume that's nothing is completely safe. haha
But it's ok for the most cases. I'm doing that on many projects in production.

**Comment by jorgeluisrezende** [comment]
oh thanks for the help!!
