### ISSUE TITLE
Tests fail and getting 404 on trying to authenticate also all semicolons missing

### ISSUE THREAD

**Issue by nottinhill** [diegohaz/rest#151]
I don't know what I can say to this code quality. Nothing works (as in subject) and also I do not see one single semicolon used. This is JavaScript, guys!

**Comment by diegohaz** [comment]
About semicolons: https://github.com/diegohaz/rest/issues/20#issuecomment-254573320

About tests and 404: everything is ok on a clean install (using generator defaults). Maybe there's an option that wasn't tested within the generator and is failing. Could you provide instructions to reproduce the issue?

**Comment by maustand** [comment]
Probably if you could tell us where there is a error and the steps to reproduce it....

This would be nicer than trolling us without care that it is a open source project where people are putting their working time without any payment

Anyway @nottiinhill this is GitHub, PR's are welcome.

Regards

**Comment by nottinhill** [comment]
Sure I'm the troll reporting that you don't adhere to simple JS code standards, published in countless books and tutorials since 1998. Any of the many linters out there would scream at your JS code. This is not CoffeeScript or Python.

Anyway I am glad if I can be of any help, even though I have moved to another code base. This is the errors I got after first test run, vanilla install:

```
Test Suites: 2 failed, 5 passed, 7 total
Tests:       14 failed, 70 passed, 84 total
Snapshots:   0 total
Time:        3.684s 
```
all related to:
```
/password-resets
```

Then:
```
● view › returns simple view

    TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
```

and

```
  ● view › returns simple view

    TypeError: Cannot read property 'view' of undefined
```

Also:

```
> jest "src/**/!(index).test.js"

  Invalid testPattern src/**/!(index).test.js supplied. Running all tests instead.
```
When I run dev server and follow your tutorial I get:

```
[nodemon] restarting due to changes...
[nodemon] starting `node .`
Express server listening on http://127.0.0.1:9000, in development mode
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })
Mongoose: passwordresets.ensureIndex({ user: 1 }, { background: true })
Mongoose: users.ensureIndex({ name: 1 }, { background: true })
Mongoose: passwordresets.ensureIndex({ token: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ keywords: 1 }, { background: true })
Mongoose: passwordresets.ensureIndex({ createdAt: 1 }, { expireAfterSeconds: 3600, background: true })
POST /users 404 13.813 ms - 145
```

**Comment by diegohaz** [comment]
First of all, there's no such thing as a single code standard in JS. There're many of them and developers follow the one they like most, or a mix of them. That's one of the reasons we have eslint in this project. If you want semicolons, just add the rule to the `.eslintrc` file and run `npm run lint -- --fix`.

I'm now able to reproduce the issue. Upgrading `rand-token` should fix it.

Regarding to test pattern issue, it seems that jest upgraded it since we wrote those scripts. We need to figure out the new pattern.

**Comment by nottinhill** [comment]
Glad you could find the issue and fix it. For the JavaScript bit I recommend reading Douglas Crockford's JavaScript The Good Parts in order to learn how to use the language properly.

**Comment by maustand** [comment]
@nottinhill 

I dont know why you are continue to trolling us without sense.

Firstly THERE IS not a single code standard for JavaScript and as you seems that you readed the Douglas's book.. All the time he speaks and writes about his Point of view and his experience....

Although i have a lots of things in common with Douglas and his point of view about how you could avoid errors and common traps in javascript...  He is not the god of Javascript and i am pretty sure that another JS stars like John resign can agree or not with him..

Personally we get agree that if you enforce the use of semicolons, you could avoid problems like the problem with the semicolon insertion in a return sentence but it is not

You can not say that this project is a shit because we use "" instead of  '' or we prefer use promises instead async await or automatic semicolon insertion instead of writing it.

This project contains and use ESLINT with our custom configuration.... you dont like ? Change it in your local env.
Probably you will scream as little child when you see that there are very old files where we use var instead let or const.....
and you know why ??

THIS IS OPEN SOURCE PROJECT.....
WE WORK IN THIS PROJECT IN OUR SPARE TIME
WE TRY TO FIX&IMPROVE THE MOST RELEVANT.
WE DONT WORK FOR U....

Everything is about the attitude that you are taking with us
Instead of helping us , you create a trolling post in order to show us " I know more that you guys " and you dont let us to know where is the bug and your observations about the code and offering us help or a single pull request....

NO.. you prefer be a stupid child and not a adult, saying us that this is Javascript and it is not python ( as we would not know it.... ) and bla bla...

Take it easy.. If you dont like.. Dont use it..
anyway....  I say it AGAIN... This is github.. PR's are welcome...
