### ISSUE TITLE
How to query a get method?

### ISSUE THREAD

**Issue by UrbanSwati** [diegohaz/rest#154]
Hey, can you make an example on how to use the q (regex) query?

![image](https://user-images.githubusercontent.com/30931804/37086356-0ca96f56-2200-11e8-8d43-d656e64dd1aa.png)

Let's say I want posts that have been posted by a certain user, how do I query that?

**Comment by maustand** [comment]
HI @UrbanSwati 

PLEASE dont open another post for asking the same. you have the post  #150 where you asked the same.

You should read the documentation of querymen as i replied you in order to ask how you can do a query, using regex.

Anyway if you want to mean about how querymen works in the generator, the "q" is only a parameter that it would expect the mongo aggregation pipelines that you want to use in your query...

```

// if it querymen gets something like : 
querymen = {
  query: { _id:  "MyUSerID"},
select : {},
cursor: {}

}

// it should be applied in this way: 
export const index = ({ querymen: { query, select, cursor } }, res, next) =>
  User.find(query, select, cursor)

```


Regards

**Comment by UrbanSwati** [comment]
Thanks, apologise for opening another issue

**Comment by maustand** [comment]
@UrbanSwati  it helps you ?

Can i close it ?
Let me know. 

Regards =)

**Comment by UrbanSwati** [comment]
It's okay, I will do so. thanks again
