### ISSUE TITLE
Update for mockgoose

### ISSUE THREAD

**Issue by cristin** [diegohaz/rest#162]
Hello,

First of all, thank you for this great generator, is very helpful and is working awesome. 

I have some issues running the tests, mostly because mockgoose is at an older version and I get some errors there. Wanted to ask if you are planning a new release that might update this?

Thank you!

**Comment by maustand** [comment]
Hi @cristin 

Currently we are working for release a new version where we will update all the dependencies again and tests, including mockgoose.

Probably you have a problem because mockgoose changed the way for preparing the storage and mock your models..

You could see this in the mockgoose documentation and you could edit it in your project at test/setup.js//

In a few days we are going to release a new version.. so just wait for it =)

**Comment by cristin** [comment]
Hi @maustand ,

Thank you for your reply. I saw where the issues were, I was just wondering if we should make this changes or just wait for a new update if is on its way.

Thank you!

**Comment by maustand** [comment]
@cristin i think that it would be up to you.
Currently i am dealing with a problem with mockgoose and jest, so i think to finish in there days..

anyway if you want to go ahead and you get some problem and you fix it, let us to know how you did it and i would add it to the generator.

Regarads..

**Comment by pedro-victor** [comment]
I believe this issue is now resolved on our master branch, since we moved away from mockgoose to [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server) ([more details here](https://github.com/diegohaz/rest/pull/174#issuecomment-389007180)).
I will close it for now.
