### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by irishabh96** [diegohaz/rest#222]
Hi, I'm using this starter for long, it would be great if you could update this with some new addons such as async-await, declaring model fields name with their types, 2FA, etc. This starter is amazing and many developers use this for their projects.

P.S. - Just a request.

**Comment by piotros** [comment]
I'm affraid that this project is no longer maintained.

**Comment by pedro-victor** [comment]
Declaring model fields with their types (and have tests created based on those types) would be a very nice addition indeed.
2FA is a little bit more complicated to do without some discussion, since we would have to implement it in an opinionated fashion (eg using Twilio SMS, similar to current password reset with Sendgrid).

I've used this generator a lot throughout the years as well and lately it's been 100% used for microservices generation (and I think this generator was somewhat initially aimed for monoliths). Some improvements could also be made for this use case (Dockerfile, services registration/discovery, ...).

**Comment by diegohaz** [comment]
> I'm affraid that this project is no longer maintained.

I don't have time to update the project, but I'm still looking into pull requests when people request my review.
