### ISSUE TITLE
Passing MASTER_KEY from client

### ISSUE THREAD

**Issue by richbrill** [diegohaz/rest#67]
Just a question really,

In the README.md under 'Authenticate the user (sign in):' is it not insecure to pass a master key from the client? or have I simply misunderstood the correct usage of it here?

**Comment by diegohaz** [comment]
`MASTER_KEY` protects endpoints when you don't have any other key to do the job (e.g. when creating a new user).

That said, the registration process must be done on the server side of your application so the key will not be exposed to the client. If it isn't possible, you should remove the master key protection and make some kind of ORIGIN verification on the API.

**Comment by richbrill** [comment]
Thanks @diegohaz very useful info, perhaps it could be added to the README.md as a use case?

**Comment by diegohaz** [comment]
Sure. Would you mind to send a PR with that?

**Comment by richbrill** [comment]
Of course

**Comment by richbrill** [comment]
@diegohaz If I understood you correctly, this would mean most users probably wouldn't need to set a master key when going to /auth which means removing the call to `master()` from the generation api/auth/index.js, do you agree?

**Comment by diegohaz** [comment]
I agree, but we would need to provide a secure method of validating origin urls or some other kind of protection.

Leaving those endpoints without any protection is a security issue as one can use them to indefinitely create resources on our server.

**Comment by richbrill** [comment]
OK, I think i'll leave the README.md as-is for now. Thanks!

**Comment by khelkun** [comment]
@diegohaz Sorry to raise up the subject but I'm a bit puzzled too by this. Let's say I have your REST backend server and I have another server that serves the frontend. The login page is rendered client side so when the user clicks on the  "sign in" I have to send a request to the _auth/_ api of the REST backend which includes the MASTER_KEY. But I don't understand how I could do that without exposing the MASTER_KEY on the client side as you said before:
> That said, the registration process must be done on the server side of your application so the key will not be exposed to the client.
You were talking about the registration process but it's also true for the authentication process if I decide to use the MASTER_KEY validation on the _auth_ api.

**Comment by Martinsos** [comment]
First of all, @diegohaz thank you for this great project! It helped me start quickly and with best practices, and I love the generator.
I am also puzzled by the concept of master key. I know about the idea of using it between the services to access each other, e.g. server1 could use server2's mater key to access it. However, as soon as master key is sent to client, it is not a secret any more, which seems to defeat it's purpose. Even if you do server rendering, master key can still be obtained, correct? I don't see how is server rendering more secure in this case.
Thank you!

**Comment by diegohaz** [comment]
> However, as soon as master key is sent to client, it is not a secret any more, which seems to defeat it's purpose. 

Hi, @Martinsos. That's true and that's why you should not send the master key (I agree that the name could be better) to the client (I mean, the browser, the JavaScript bundle etc.).

If you do server rendering (with Rails, PHP, Node etc.), you are able to keep part of your code hidden from the client.

**Comment by Martinsos** [comment]
Could you please explain in more details how are you able to keep part of
your code hidden if you are doing server side rendering?

On Aug 30, 2017 2:02 AM, "Haz" <notifications@github.com> wrote:

However, as soon as master key is sent to client, it is not a secret any
more, which seems to defeat it's purpose.

Hi, @Martinsos <https://github.com/martinsos>. That's true and that's why
you should not send the master key (I agree that the name could be better)
to the client (I mean, the browser, the JavaScript bundle etc.).

If you do server rendering (with Rails, PHP, Node etc.), you are able to
keep part of your code hidden from the client.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/diegohaz/rest/issues/67#issuecomment-325847393>, or mute
the thread

**Comment by diegohaz** [comment]
@Martinsos Try the `redux-ssr` branch of this repo: https://github.com/diegohaz/arc

`src/server.js` is only executed on server side, thus none of its contents is exposed to the client.

**Comment by Martinsos** [comment]
@diegohaz Thanks! I am looking at it, but I am not sure what to conclude
from it -> what am I looking for? Could you just describe the concept
shortly in words? I dont see any master key being used here.

I am assuming that you maybe ment the following: we have two servers, one
serving the webapp and one serving the api server. Webapp server has the
master key, and when it serves the js/html, request from js/html goes
through the webapp server who then uses master key to make the actual auth
request to the api server? Is that it?
But in that case, it is just one extra step, again anybody can send that
request to webapp server. Except if it has CORS, but in that case you could
have also had CORS on the api server, so again there is no need for master
key. I hope I am not asking too much, but I would really like to understand
what is the thing with the master key!

**Comment by diegohaz** [comment]
Your thoughts were correct, except that you will not expose a public rest endpoint on your webapp server. Instead, you will render an html form using `method=POST` and `action=/your_endpoint`.

Then, in the webapp server, `/your_endpoint` will respond to the POST request. That's different than an usual rest api request. The `content-type`, for example, will be `application/x-www-form-urlencoded` or `multipart/form-data`, instead of the `application/json` you usually receive in a REST API. 

Of course, one can still forge that request or even create a fake page with a form with `action=https://yoursite.com/your_endpoint`. This exploit is called CSRF and is very easy to avoid. If you are using Node+Express, for example, you can use https://github.com/expressjs/csurf to protect agains CSRF attacks making sure the form that sent the data was generated by the same server that is processing the request.

**Comment by diegohaz** [comment]
Also, CORS is a browser protection. You should not rely on it as one can always request your API using `curl`.

**Comment by Martinsos** [comment]
Alright great, I did not know all this! I knew about CORS (going by with
curl), but I did not know that I can make sure that the form that sent the
data was generated by the same server. I will explore this further to learn
more, thank you for sharing.
Concluding from this, I think it might be good to somehow mention this in
the project, to explain when to use the master key and when not to. I think
big part of people will just assume they should use master key directly
from their SPA, not really thinking too much about the cases in which it
actually makes sense -> this is a rest api server and often we think about
using it directly with the SPA that is served on who knows what kind of
simple server, without any server rendering.

**Comment by diegohaz** [comment]
Yeah, I agree. I would really appreciate a PR adding it to README.

You can still use it with SPA, without server rendering, but you will need to implement some other kind of secure method. I'm not aware of one. This is a very desirable PR as well.

**Comment by hboylan** [comment]
@diegohaz It seems like the MASTER_KEY should be removed by default. You mentioned that the registration endpoint will be insecure https://github.com/diegohaz/rest/issues/67#issuecomment-286531368, but the common solution for this is to add captcha and email verification.

I believe your generator prompted me to integrate SendGrid for password reset. Would it be a difficult PR to implement email verification with that as well?

**Comment by psotos** [comment]
After reading all of this, I believe that the master key requirement should be removed from the login section. In this way, a normal user can attempt to login from an SPA without the master key. This is a norm in most apps.

**Comment by diegohaz** [comment]
I see your point, @psotos. But if we were to remove that, we would need to provide an alternative protection out of the box (and I'm open for suggestions and PRs). Otherwise, anyone can log in your server from anywhere.

I know that most of people don't care about it. Most don't even know the security issues of unprotected endpoints. But having this as an opt out option (which is as easy as removing one line of code) at least makes them to think about it and choose consciously.

**Comment by psotos** [comment]
They would still need valid credentials. I am only talking about removing the master key need from the login  endpoint. There are other ways to make it harder to hack like blocking a username from its ability to login for 1 hour after 3 or 5 failed login attempts, etc.

**Comment by DanMMX** [comment]
I'm not a security master, so if you could tell us (explained) another way to protect those master keys endpoints I might be able to work on it @psotos

Regards

**Comment by psotos** [comment]
Dan,

The whole point is that you DON'T protect a login endpoint, otherwise, people can't login! You don't want to have to have users knowing a master key to log in. So take off the master key necessity from the login endpoint. Someone with a valid username and password SHOULD be able to log in.

**Comment by DanMMX** [comment]
Peter

The idea of the master key is to be used by the application (from wherever you consume your rest server), not for the users. I'm pretty sure you don't ask your end clients to curl into your server, instead you would write up a user interface to interact with.

The thing with removing the master key in the log in is to avoid unwanted crawlers trying to log in with countless combinations of emails + passwords in an indefinite way.

Instead I recommend you to consider the master key as part of your user faced application. Putting here an example using Axios, Redux and Electron:


```
// request.js
import axios from 'axios';
import { SubmissionError } from 'redux-form';
import { ipcRenderer } from 'electron';

import { LOG_IN, RECEIVED_USER } from '../actions/auth';

const API = process.env.NODE_ENV === 'development' ? 'http://localhost:9000/' : 'http://casacuesta.juancaspro.webfactional.com/';
// const API = 'http://localhost:9000/';
// const API = 'http://casacuesta.juancaspro.webfactional.com/';
const MASTER_KEY = process.env.MASTER_KEY || '1Qejzgqm7HMYh5D4n1mH0q4nzArEPQUR';
const email = process.env.EMAIL || 'branch@branch.com';
const password = process.env.PASSWORD || '123456';

axios.defaults.baseURL = API;

axios.interceptors.response.use(response => response, ({ response: { data, status } }) => {
  if ([400, 409].indexOf(status) >= 0 && (!data.type || data.type !== 'EeagerLoading')) {
    let errObj = {};

    if (data.errors) {
      Object.keys(data.errors).forEach(key => {
        errObj[key] = data.errors[key].message;
      });
    } else {
      errObj = {
        [data.param]: data[data.name] ? data[data.name] : data.message
      };
    }

    throw new SubmissionError(errObj);
  }

  // Do something with response error
  return Promise.reject(data);
});

export default axios;

export function auth(dispatch) {
  return axios.post('/auth', {
    access_token: MASTER_KEY
  }, {
    auth: { username: email, password }
  })
  .then(({ data: { token, user } }) => {
    dispatch({ type: LOG_IN, payload: token });
    return dispatch({ type: RECEIVED_USER, payload: user });
  })
  .catch(console.log);
}

export function setAuthToken(token) {
  ipcRenderer.send('set-auth-token', token);
  axios.defaults.headers.common.Authorization = `Bearer ${token}`;
}
```

**Comment by psotos** [comment]
Its a single page app that I am writing. It will be communicating directly with the API. 

"The thing with removing the master key in the log in is to avoid unwanted crawlers trying to log in with countless combinations of emails + passwords in an indefinite way."
There are lots of ways to handle this but here is one reasonable and widely used approach:

Write an algorithm which locks out users who make multiple bad requests by banning their IP. I can go into the full algorithm if you like but for the most part its a user lock out/IP banning approach.

How do I write an SPA with this Master Key problem? You have to admit that this is not a standard approach taken by others which is why people like me keep bringing it up.

**Comment by psotos** [comment]
One last thought, are Google, Microsoft, Twitter, LinkedIn, or any other large company with a huge userbase, subject to massive attacks by hackers using your master key approach for securing login urls? No they are not. They have other mechanisms for sure, but not this highly unusual mechanism for secure an endpoint, which by definition needs to be open. Anyway, I'm not trying to be pushy or annoying just trying to debate what is the more accepted mechanism for login type urls.

**Comment by DanMMX** [comment]
> There are lots of ways to handle this but here is one reasonable and widely used approach:

>Write an algorithm which locks out users who make multiple bad requests by banning their IP. I can go into the full algorithm if you like but for the most part its a user lock out/IP banning approach.

PRs welcome 😃 

> How do I write an SPA with this Master Key problem? 
I don't see it as a problem, and also [this code](https://github.com/diegohaz/rest/issues/67#issuecomment-414715619) is for a SPA

> You have to admit that this is not a standard approach taken by others which is why people like me keep bringing it up.
I've seen it in different projects (old projects)

If this is really a problem for you all you need to do is remove the `master()` middleware on any endpoints you have it in

**Comment by psotos** [comment]
Dan,

The code that you are referring to appears to be "server based", so some middle ware which sits between the SPA and the Endpoint. I'm not going to have such middle ware. 

It's all good though, I will just remove the master protection from the login. I suggest a flag for generating code with an unprotected login.

I will think of some anti-login-spamming techniques and eventually push them as a PR. Again this project is amazing and I am very appreciative of the work put into it so far.

**Comment by Martinsos** [comment]
@psotos if I am correct, that is Electron based app that reads master key from the environment. So while it is a client in a sense, it is not what you meant by client code, which is an SPA, where you can't provide master key through the environment or with any similar mechanism.

**Comment by DanMMX** [comment]
Yes @psotos , the consumer app should know the _precious_ `MASTER_KEY`. You can put it in a variable or somewhere else, there I'm taking it from the env variables, but however you're building your SPA you can put it on any kind of variable or retrieve it in any way you want.

**Comment by psotos** [comment]
Dan,

But my SPA code will only be served by the host, and not read any environment variables, and definitely not deliver them to the client side app. This is where I am confused. How does the client app, while running in the clients browser, gain access to the Master Key? Also, if it did, that would be a huge security hole since it would be visible to the client via the browsers dev tools, and therefore exposed. This is why I used the word precious. :)

**Comment by DanMMX** [comment]
Peter

I get that. Of course I don't use that on production, that gets built and compiled to compressed code. The only way that the client app, while running in the clients browser will gain access to the Master Key is if you put it in the code explicitly. Such as `window.MASTER_KEY = 'aosidjoqiwjeoiqjwd'` or something like that.

As we've been mentioning, the only purpose of the MASTER_KEY is to protect the log in endpoint (or whatever endpoints you decide), so attacks would need a little bit more effort to attack your endpoints.

**Comment by Martinsos** [comment]
@DanMMX sorry to interrupt, but what do you use in production, for SPA, then? Can you give an exact example of how you use SPA with master key?

Because if you have it in your SPA code, it does not matter if it gets compiled, compressed, obfuscated or whatever, string values (and master key is string value) are always public at the end. You can make them in theory much harder to read, but they will always be readable in some way. So you can't consider that a security mechanism, quite the opposite, it gives false feeling of security.

But @diegohaz  was previously mentioning some different mechanisms, like serving a form directly from server, outside of SPA, so I thought that was the approach? Although I have to admit I don't really understand how would that solution go, I have not given enough time into researching what Diego said there.

**Comment by psotos** [comment]
@Martinsos I concur as his is exactly what I am saying. Having a master key for login from an SPA just doesn't make sense. Guys please put a flag in your tool to disable this "feature".

**Comment by DanMMX** [comment]
I'd prefer to have a log in endpoint protected by a MASTER_KEY (even when it's public) for some generic attacks instead of a completely public endpoint. As I've mentioned previously, I'm not an expert on security and PRs to improve security are gently accepted.

**Comment by psotos** [comment]
@DanMMX The problem is, in an SPA, the only way to implement this master key concept is to pass it to the browser, which as @Martinsos mentioned makes the app WAY less secure. How does a user, let's say our Russian Trollbot LOL, log into our app? Do we email him the master key? Pass it up to the browser? Both of these are wildy unsecure because we know our Master Key will end up on Wikileaks! As you can see, there is no secure way to get this Master Key to the user to ensure that they don't put it out in the wild. This is why no major websites are implementing this type of protection. If you want security from concentrated hacking attempts, people tend to implement ip blocking and or user account locking for repeated failed password attempts.

**Comment by diegohaz** [comment]
I'm sorry about the delay. I'm gonna try to explain some things.

## Why does `MASTER_KEY` exist?

When exposing POST/PUT/PATCH endpoints - that is, endpoints that create or modify resources on your server -, you have to protect them somehow. Usually, that protection is a user token acquired via login.

For authentication (signin/signup) endpoints, though, we don't have that protection. So, `MASTER_KEY` is a trivial yet efficient way to cover that. 

If you're doing SPA, you should definitely go for another approach. But, **it's better to keep MASTER_KEY than having no protection at all**, even in SPAs, even exposing the key on the browser. That's why we **won't** remove it from this generator by default, unless someone come up with a better and equally easy solution.

## How can we protect authentication in SPAs?

I'm not a big fan of password authentication in SPAs. I prefer to render those forms via server when I need to provide them. 

The easiest and most secure way to do auth in SPAs is to avoid the password method at all and rely on social authentication. When using this generator, you just need to make sure to [set your Facebook app secret](https://github.com/diegohaz/rest/issues/71#issuecomment-289208524). This way you're delegating the protection to Facebook.

If you still want to do password authentication in SPA, I recommend you to find and implement another kind of protection. If you don't, keeping `MASTER_KEY` is better than nothing. And, again, that's why we **won't** remove it from this generator by default.

## How do I remove `MASTER_KEY` protection on a specific endpoint?

Just remove this line:
https://github.com/diegohaz/rest/blob/83cc9c38fd14db10188b9d2e4bc485e6a7f803e7/generators/app/templates/api/auth/index.js#L31

## How do I create server rendered forms in "SPA"?

It depends on the library/framework you're using. In React, you can use the same code for server and client and handle POST requests like you would do in a non-SPA.

This is an example of a form rendered on the server in React (disable JavaScript): https://arc.diegohaz.com/sample-page

- [This line](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/containers/SamplePage.js#L9-L14) is responsible for handling the POST request on the server. 
- That static method is called [here](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/server.js#L60), which is a similar approach to [Next.js](https://github.com/zeit/next.js)' `static getInitialProps`.
- Since the form can be sent via HTML, we have to protect it against [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks (yes, every approach has its own kind of security concerns).
- The CSRF token [is set](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/server.js#L37) in a redux store (see the [reducer](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/store/form/reducer.js#L10) and the [action](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/store/form/actions.js#L3-L6)) and [put](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/containers/PostForm.js#L19) in a [field](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/components/organisms/PostForm/index.js#L17) named `_csrf` in the form.
- When receiving the POST request, the [csurf](https://github.com/expressjs/csurf) express [middleware](https://github.com/diegohaz/arc/blob/179458033e737eb833521cfbdddbedc4da2f0466/src/server.js#L25) will check that field.

## `MASTER_KEY` will end up on Wikileaks!

Then you invalidate it and generate a new one. If you had no protection, you could do nothing anyway.

## Why don't we do like Google, Twitter, Microsoft, LinkedIn etc.?

These companies have security experts working for them. I'd love to provide the same approaches they use here, but I'm not good enough, sorry. 😅

But, well, all those companies, at least on their main products, render their authentication pages on the server and handle form submits via HTTP request (not ajax).
